spring:
  servlet:
    multipart:
      enabled: true # 멀티파트 업로드 지원여부 (default: true)
      file-size-threshold: 0B # 파일을 디스크에 저장하지 않고 메모리에 저장하는 최소 크기 (default: 0B)
      location: /Users/hyeonseok/Desktop/AWS # 업로드된 파일이 임시로 저장되는 디스크 위치 (default: WAS가 결정)
      max-file-size: 100MB # 한개 파일의 최대 사이즈 (default: 1MB)
      max-request-size: 100MB # 한개 요청의 최대 사이즈 (default: 10MB)
  # MAIL
  mail:
    host: smtp.naver.com
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.naver.com
          starttls: true
  # DB Settings
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/space
    username: hyeonseok
    password:
  #  datasource:
  cache:
    type: redis
  data:
    redis:
      host: localhost  # Redis 호스트 주소
      port: 6379       # Redis 포트
      database: 0      # Redis 데이터베이스 번호
      lettuce:
        pool:
          max-active: 8  # 최대 활성 커넥션 수
          max-idle: 8    # 최대 유휴 커넥션 수
          min-idle: 2    # 최소 유휴 커넥션 수
          max-wait: -1   # 최대 대기 시간 (-1은 무제한)
      password:
  # Hibernate
  jpa:
    hibernate:
      ddl-auto: update

#JWT
auth:
  jwt:
    issuer: team.sparta.com
    secret: 52DANSJDNASJnjdgsnjFDNJSDFSDFDSF
    accessTokenExpirationMinutes: 30
    refreshTokenExpirationDays: 1
    setFrom: abczza@naver.com

# Log
logging:
  level:
    org.hibernate.sql: debug

